### ISSUE TITLE
Хранение предметов

### ISSUE THREAD

**Issue by GreatAtom** [AndreyBritvin/TLSQ_bot#1]
Предметы лучше хранить в JSON (как сделано для настроек).  И сделать всего один метод/класс для их парсинга.  Так будет проще добавлять новые предметы (даже не редактируя исходный код).
       
     self.russian = {
            "Бегемот?": ["-бег-", "-бегем-", "-бегемот-"],
                                       ................
            }
   Не забывай применять комбинацию клавишей Cntrl + L.

**Comment by GreatAtom** [comment]
Чтобы файлы не плодить в проекте. Создай для файлов с предметами отдельную папку subjects, например.

Хорошо бы автоматизировать их подгрузку в бота. Можно создать словарь и перебирать все фалы в папке subjects, считывать содержимое, ключами которого будут названия этих файлов. 
Тогда для добавления нового предмета достаточно будет добавить файл в папку.

**Comment by AndreyBritvin** [comment]
Спасибо за совет. Принял к сведению. На данный момент я сделал все предметы в отдельных json файлах. Автозагрузку сделаю чуть позжу

**Comment by AndreyBritvin** [comment]
Я создал папку subjects и положил в нее главный файл с предметами и сами файлы с вопросами. Через другой файл они загружаются и нагрузка на бота благодаря этому снизилась. Добавил автозагрузку.
